#!/usr/bin/env bash 
touch /var/run/myscript.pid
pgrep -f /var/run/myscript.pid | cat > /var/run/myscript.pid
digterm(){
 echo "I hate the kill command"
 rm /var/run/myscript.pid
 exit 0
}
trap 'digterm' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm /var/run/myscript.pid' SIGQUIT

while true ; do 
 echo "To infinity and beyond"
 sleep 2
done
