#!/usr/bin/env bash 
#   Create a file /var/run/myscript.pid containing the script PID.
#   Displays "To infinity and beyond" indefinitely
#   Displays "I hate the kill command" upon receiving a SIGTERM
#   Displays "Y U no love me?!" upon receiving a SIGINT
#   Deletes the file /var/run/myscript.pid and terminates upon
#+  receiving a SIGQUIT or SIGTERM.
touch /var/run/myscript.pid
echo $$| cat > /var/run/myscript.pid
digterm(){
 echo "I hate the kill command"
 rm /var/run/myscript.pid
 exit 0
}
trap 'digterm' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm /var/run/myscript.pid' SIGQUIT

while true ; do 
 echo "To infinity and beyond"
 sleep 2
done
